[package]
name = "ndarray_numeric"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
num-traits = "0.2"
ndarray = "0.15"
duplicate = "0.4"